/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { AbstractSetRemovalTimeDto } from './models/AbstractSetRemovalTimeDto';
export type { AbstractVendorVersionInformationDto } from './models/AbstractVendorVersionInformationDto';
export type { ActivityInstanceDto } from './models/ActivityInstanceDto';
export type { ActivityInstanceIncidentDto } from './models/ActivityInstanceIncidentDto';
export type { ActivityStatisticsResultDto } from './models/ActivityStatisticsResultDto';
export type { AnnotationDto } from './models/AnnotationDto';
export type { AnyValue } from './models/AnyValue';
export type { AtomLink } from './models/AtomLink';
export type { AttachmentDto } from './models/AttachmentDto';
export type { AuthenticationResult } from './models/AuthenticationResult';
export type { AuthorizationCheckResultDto } from './models/AuthorizationCheckResultDto';
export type { AuthorizationCreateDto } from './models/AuthorizationCreateDto';
export type { AuthorizationDto } from './models/AuthorizationDto';
export type { AuthorizationExceptionDto } from './models/AuthorizationExceptionDto';
export type { AuthorizationUpdateDto } from './models/AuthorizationUpdateDto';
export type { BasicUserCredentialsDto } from './models/BasicUserCredentialsDto';
export type { BatchDto } from './models/BatchDto';
export type { BatchStatisticsDto } from './models/BatchStatisticsDto';
export type { CalledProcessDefinitionDto } from './models/CalledProcessDefinitionDto';
export type { CamundaFormRef } from './models/CamundaFormRef';
export type { CaseDefinitionDto } from './models/CaseDefinitionDto';
export type { CheckPasswordPolicyResultDto } from './models/CheckPasswordPolicyResultDto';
export type { CheckPasswordPolicyRuleDto } from './models/CheckPasswordPolicyRuleDto';
export type { CleanableHistoricBatchReportResultDto } from './models/CleanableHistoricBatchReportResultDto';
export type { CleanableHistoricDecisionInstanceReportResultDto } from './models/CleanableHistoricDecisionInstanceReportResultDto';
export type { CleanableHistoricProcessInstanceReportResultDto } from './models/CleanableHistoricProcessInstanceReportResultDto';
export type { CommentDto } from './models/CommentDto';
export type { CompleteExternalTaskDto } from './models/CompleteExternalTaskDto';
export type { CompleteTaskDto } from './models/CompleteTaskDto';
export { ConditionQueryParameterDto } from './models/ConditionQueryParameterDto';
export type { CorrelationMessageAsyncDto } from './models/CorrelationMessageAsyncDto';
export type { CorrelationMessageDto } from './models/CorrelationMessageDto';
export type { CountResultDto } from './models/CountResultDto';
export type { CreateFilterDto } from './models/CreateFilterDto';
export type { CreateIncidentDto } from './models/CreateIncidentDto';
export type { DecisionDefinitionDiagramDto } from './models/DecisionDefinitionDiagramDto';
export type { DecisionDefinitionDto } from './models/DecisionDefinitionDto';
export type { DecisionRequirementsDefinitionDto } from './models/DecisionRequirementsDefinitionDto';
export type { DecisionRequirementsDefinitionXmlDto } from './models/DecisionRequirementsDefinitionXmlDto';
export type { DeleteHistoricDecisionInstancesDto } from './models/DeleteHistoricDecisionInstancesDto';
export type { DeleteHistoricProcessInstancesDto } from './models/DeleteHistoricProcessInstancesDto';
export type { DeleteProcessInstancesDto } from './models/DeleteProcessInstancesDto';
export type { DeploymentDto } from './models/DeploymentDto';
export type { DeploymentResourceDto } from './models/DeploymentResourceDto';
export type { DeploymentWithDefinitionsDto } from './models/DeploymentWithDefinitionsDto';
export { DurationReportResultDto } from './models/DurationReportResultDto';
export type { EvaluateDecisionDto } from './models/EvaluateDecisionDto';
export type { EvaluationConditionDto } from './models/EvaluationConditionDto';
export type { EventSubscriptionDto } from './models/EventSubscriptionDto';
export { EventSubscriptionQueryDto } from './models/EventSubscriptionQueryDto';
export type { ExceptionDto } from './models/ExceptionDto';
export type { ExecutionDto } from './models/ExecutionDto';
export type { ExecutionQueryDto } from './models/ExecutionQueryDto';
export type { ExecutionTriggerDto } from './models/ExecutionTriggerDto';
export type { ExtendLockOnExternalTaskDto } from './models/ExtendLockOnExternalTaskDto';
export type { ExternalTaskBpmnError } from './models/ExternalTaskBpmnError';
export type { ExternalTaskDto } from './models/ExternalTaskDto';
export type { ExternalTaskFailureDto } from './models/ExternalTaskFailureDto';
export type { ExternalTaskQueryDto } from './models/ExternalTaskQueryDto';
export type { FetchExternalTasksDto } from './models/FetchExternalTasksDto';
export type { FetchExternalTaskTopicDto } from './models/FetchExternalTaskTopicDto';
export type { FilterDto } from './models/FilterDto';
export type { FormDto } from './models/FormDto';
export type { GroupDto } from './models/GroupDto';
export type { GroupQueryDto } from './models/GroupQueryDto';
export type { HandleExternalTaskDto } from './models/HandleExternalTaskDto';
export type { HistoricActivityInstanceDto } from './models/HistoricActivityInstanceDto';
export type { HistoricActivityInstanceQueryDto } from './models/HistoricActivityInstanceQueryDto';
export type { HistoricActivityStatisticsDto } from './models/HistoricActivityStatisticsDto';
export type { HistoricBatchDto } from './models/HistoricBatchDto';
export type { HistoricBatchQueryDto } from './models/HistoricBatchQueryDto';
export type { HistoricDecisionInputInstanceDto } from './models/HistoricDecisionInputInstanceDto';
export type { HistoricDecisionInstanceDto } from './models/HistoricDecisionInstanceDto';
export type { HistoricDecisionInstanceQueryDto } from './models/HistoricDecisionInstanceQueryDto';
export type { HistoricDecisionInstanceStatisticsDto } from './models/HistoricDecisionInstanceStatisticsDto';
export type { HistoricDecisionOutputInstanceDto } from './models/HistoricDecisionOutputInstanceDto';
export type { HistoricDetailDto } from './models/HistoricDetailDto';
export type { HistoricDetailQueryDto } from './models/HistoricDetailQueryDto';
export type { HistoricExternalTaskLogDto } from './models/HistoricExternalTaskLogDto';
export type { HistoricExternalTaskLogQueryDto } from './models/HistoricExternalTaskLogQueryDto';
export type { HistoricIdentityLinkLogDto } from './models/HistoricIdentityLinkLogDto';
export type { HistoricIncidentDto } from './models/HistoricIncidentDto';
export type { HistoricJobLogDto } from './models/HistoricJobLogDto';
export type { HistoricJobLogQueryDto } from './models/HistoricJobLogQueryDto';
export { HistoricProcessInstanceDto } from './models/HistoricProcessInstanceDto';
export { HistoricProcessInstanceQueryDto } from './models/HistoricProcessInstanceQueryDto';
export type { HistoricTaskInstanceDto } from './models/HistoricTaskInstanceDto';
export type { HistoricTaskInstanceQueryDto } from './models/HistoricTaskInstanceQueryDto';
export { HistoricTaskInstanceReportResultDto } from './models/HistoricTaskInstanceReportResultDto';
export type { HistoricVariableInstanceDto } from './models/HistoricVariableInstanceDto';
export type { HistoricVariableInstanceQueryDto } from './models/HistoricVariableInstanceQueryDto';
export type { HistoryCleanupConfigurationDto } from './models/HistoryCleanupConfigurationDto';
export type { HistoryTimeToLiveDto } from './models/HistoryTimeToLiveDto';
export type { IdentityLinkDto } from './models/IdentityLinkDto';
export type { IdentityServiceGroupDto } from './models/IdentityServiceGroupDto';
export type { IdentityServiceGroupInfoDto } from './models/IdentityServiceGroupInfoDto';
export type { IdentityServiceUserDto } from './models/IdentityServiceUserDto';
export type { IncidentDto } from './models/IncidentDto';
export type { IncidentStatisticsResultDto } from './models/IncidentStatisticsResultDto';
export { JobConditionQueryParameterDto } from './models/JobConditionQueryParameterDto';
export type { JobDefinitionDto } from './models/JobDefinitionDto';
export type { JobDefinitionPriorityDto } from './models/JobDefinitionPriorityDto';
export type { JobDefinitionQueryDto } from './models/JobDefinitionQueryDto';
export type { JobDefinitionsSuspensionStateDto } from './models/JobDefinitionsSuspensionStateDto';
export type { JobDefinitionSuspensionStateDto } from './models/JobDefinitionSuspensionStateDto';
export type { JobDto } from './models/JobDto';
export type { JobDuedateDto } from './models/JobDuedateDto';
export type { JobQueryDto } from './models/JobQueryDto';
export type { JobSuspensionStateDto } from './models/JobSuspensionStateDto';
export type { LinkableDto } from './models/LinkableDto';
export type { LockedExternalTaskDto } from './models/LockedExternalTaskDto';
export type { LockExternalTaskDto } from './models/LockExternalTaskDto';
export { MessageCorrelationResultWithVariableDto } from './models/MessageCorrelationResultWithVariableDto';
export type { MetricsIntervalResultDto } from './models/MetricsIntervalResultDto';
export type { MetricsResultDto } from './models/MetricsResultDto';
export type { MigrationExecutionDto } from './models/MigrationExecutionDto';
export type { MigrationInstructionDto } from './models/MigrationInstructionDto';
export type { MigrationInstructionValidationReportDto } from './models/MigrationInstructionValidationReportDto';
export type { MigrationPlanDto } from './models/MigrationPlanDto';
export type { MigrationPlanGenerationDto } from './models/MigrationPlanGenerationDto';
export type { MigrationPlanReportDto } from './models/MigrationPlanReportDto';
export type { MigrationVariableValidationReportDto } from './models/MigrationVariableValidationReportDto';
export type { MissingAuthorizationDto } from './models/MissingAuthorizationDto';
export type { ModificationDto } from './models/ModificationDto';
export type { MultiFormAttachmentDto } from './models/MultiFormAttachmentDto';
export type { MultiFormDeploymentDto } from './models/MultiFormDeploymentDto';
export { MultiFormVariableBinaryDto } from './models/MultiFormVariableBinaryDto';
export { MultipleProcessInstanceModificationInstructionDto } from './models/MultipleProcessInstanceModificationInstructionDto';
export type { ParseExceptionDto } from './models/ParseExceptionDto';
export type { PasswordPolicyDto } from './models/PasswordPolicyDto';
export type { PasswordPolicyRequestDto } from './models/PasswordPolicyRequestDto';
export type { PasswordPolicyRuleDto } from './models/PasswordPolicyRuleDto';
export type { PatchVariablesDto } from './models/PatchVariablesDto';
export type { PriorityDto } from './models/PriorityDto';
export type { ProblemDto } from './models/ProblemDto';
export type { ProcessDefinitionDiagramDto } from './models/ProcessDefinitionDiagramDto';
export type { ProcessDefinitionDto } from './models/ProcessDefinitionDto';
export type { ProcessDefinitionStatisticsResultDto } from './models/ProcessDefinitionStatisticsResultDto';
export type { ProcessDefinitionSuspensionStateDto } from './models/ProcessDefinitionSuspensionStateDto';
export type { ProcessEngineDto } from './models/ProcessEngineDto';
export type { ProcessInstanceDto } from './models/ProcessInstanceDto';
export type { ProcessInstanceModificationDto } from './models/ProcessInstanceModificationDto';
export { ProcessInstanceModificationInstructionDto } from './models/ProcessInstanceModificationInstructionDto';
export type { ProcessInstanceQueryDto } from './models/ProcessInstanceQueryDto';
export type { ProcessInstanceSuspensionStateAsyncDto } from './models/ProcessInstanceSuspensionStateAsyncDto';
export type { ProcessInstanceSuspensionStateDto } from './models/ProcessInstanceSuspensionStateDto';
export type { ProcessInstanceWithVariablesDto } from './models/ProcessInstanceWithVariablesDto';
export type { RedeploymentDto } from './models/RedeploymentDto';
export type { ResourceOptionsDto } from './models/ResourceOptionsDto';
export type { ResourceReportDto } from './models/ResourceReportDto';
export type { RestartProcessInstanceDto } from './models/RestartProcessInstanceDto';
export { RestartProcessInstanceModificationInstructionDto } from './models/RestartProcessInstanceModificationInstructionDto';
export type { RetriesDto } from './models/RetriesDto';
export type { SchemaLogEntryDto } from './models/SchemaLogEntryDto';
export type { SchemaLogQueryDto } from './models/SchemaLogQueryDto';
export type { SetJobRetriesByProcessDto } from './models/SetJobRetriesByProcessDto';
export type { SetJobRetriesDto } from './models/SetJobRetriesDto';
export type { SetRemovalTimeToHistoricBatchesDto } from './models/SetRemovalTimeToHistoricBatchesDto';
export type { SetRemovalTimeToHistoricDecisionInstancesDto } from './models/SetRemovalTimeToHistoricDecisionInstancesDto';
export type { SetRemovalTimeToHistoricProcessInstancesDto } from './models/SetRemovalTimeToHistoricProcessInstancesDto';
export type { SetRetriesForExternalTasksDto } from './models/SetRetriesForExternalTasksDto';
export type { SetVariablesAsyncDto } from './models/SetVariablesAsyncDto';
export type { SignalDto } from './models/SignalDto';
export type { SortTaskQueryParametersDto } from './models/SortTaskQueryParametersDto';
export type { StartProcessInstanceDto } from './models/StartProcessInstanceDto';
export type { StartProcessInstanceFormDto } from './models/StartProcessInstanceFormDto';
export type { SuspensionStateDto } from './models/SuspensionStateDto';
export type { TaskBpmnErrorDto } from './models/TaskBpmnErrorDto';
export { TaskDto } from './models/TaskDto';
export type { TaskEscalationDto } from './models/TaskEscalationDto';
export { TaskQueryDto } from './models/TaskQueryDto';
export type { TelemetryConfigurationDto } from './models/TelemetryConfigurationDto';
export type { TelemetryCountDto } from './models/TelemetryCountDto';
export type { TelemetryDataDto } from './models/TelemetryDataDto';
export type { TelemetryInternalsDto } from './models/TelemetryInternalsDto';
export type { TelemetryLicenseKeyDto } from './models/TelemetryLicenseKeyDto';
export type { TelemetryProductDto } from './models/TelemetryProductDto';
export type { TenantDto } from './models/TenantDto';
export type { TransitionInstanceDto } from './models/TransitionInstanceDto';
export type { TriggerVariableValueDto } from './models/TriggerVariableValueDto';
export type { UserCredentialsDto } from './models/UserCredentialsDto';
export type { UserDto } from './models/UserDto';
export type { UserIdDto } from './models/UserIdDto';
export type { UserOperationLogEntryDto } from './models/UserOperationLogEntryDto';
export type { UserProfileDto } from './models/UserProfileDto';
export type { VariableInstanceDto } from './models/VariableInstanceDto';
export type { VariableInstanceQueryDto } from './models/VariableInstanceQueryDto';
export type { VariableQueryParameterDto } from './models/VariableQueryParameterDto';
export type { VariableValueDto } from './models/VariableValueDto';
export type { VersionDto } from './models/VersionDto';

export { AuthorizationService } from './services/AuthorizationService';
export { BatchService } from './services/BatchService';
export { ConditionService } from './services/ConditionService';
export { DecisionDefinitionService } from './services/DecisionDefinitionService';
export { DecisionRequirementsDefinitionService } from './services/DecisionRequirementsDefinitionService';
export { DeploymentService } from './services/DeploymentService';
export { EngineService } from './services/EngineService';
export { EventSubscriptionService } from './services/EventSubscriptionService';
export { ExecutionService } from './services/ExecutionService';
export { ExternalTaskService } from './services/ExternalTaskService';
export { FilterService } from './services/FilterService';
export { GroupService } from './services/GroupService';
export { HistoricActivityInstanceService } from './services/HistoricActivityInstanceService';
export { HistoricBatchService } from './services/HistoricBatchService';
export { HistoricDecisionDefinitionService } from './services/HistoricDecisionDefinitionService';
export { HistoricDecisionInstanceService } from './services/HistoricDecisionInstanceService';
export { HistoricDecisionRequirementsDefinitionService } from './services/HistoricDecisionRequirementsDefinitionService';
export { HistoricDetailService } from './services/HistoricDetailService';
export { HistoricExternalTaskLogService } from './services/HistoricExternalTaskLogService';
export { HistoricIdentityLinkLogService } from './services/HistoricIdentityLinkLogService';
export { HistoricIncidentService } from './services/HistoricIncidentService';
export { HistoricJobLogService } from './services/HistoricJobLogService';
export { HistoricProcessDefinitionService } from './services/HistoricProcessDefinitionService';
export { HistoricProcessInstanceService } from './services/HistoricProcessInstanceService';
export { HistoricTaskInstanceService } from './services/HistoricTaskInstanceService';
export { HistoricUserOperationLogService } from './services/HistoricUserOperationLogService';
export { HistoricVariableInstanceService } from './services/HistoricVariableInstanceService';
export { HistoryCleanupService } from './services/HistoryCleanupService';
export { IdentityService } from './services/IdentityService';
export { IncidentService } from './services/IncidentService';
export { JobService } from './services/JobService';
export { JobDefinitionService } from './services/JobDefinitionService';
export { MessageService } from './services/MessageService';
export { MetricsService } from './services/MetricsService';
export { MigrationService } from './services/MigrationService';
export { ModificationService } from './services/ModificationService';
export { ProcessDefinitionService } from './services/ProcessDefinitionService';
export { ProcessInstanceService } from './services/ProcessInstanceService';
export { SchemaLogService } from './services/SchemaLogService';
export { SignalService } from './services/SignalService';
export { TaskService } from './services/TaskService';
export { TaskAttachmentService } from './services/TaskAttachmentService';
export { TaskCommentService } from './services/TaskCommentService';
export { TaskIdentityLinkService } from './services/TaskIdentityLinkService';
export { TaskLocalVariableService } from './services/TaskLocalVariableService';
export { TaskVariableService } from './services/TaskVariableService';
export { TelemetryService } from './services/TelemetryService';
export { TenantService } from './services/TenantService';
export { UserService } from './services/UserService';
export { VariableInstanceService } from './services/VariableInstanceService';
export { VersionService } from './services/VersionService';
